### ISSUE TITLE
Classes em falta

### ISSUE THREAD

**Issue by rudiluis** [jpcmt/pa2015-inspector#2]
import extensionpoints.ISearchEvent;
import extensionpoints.ISearchEventListener;

**Comment by jpcmt** [comment]
Bom dia

Isso é porque estou a usar serviço do deepsearch, então tens que fazer o
clone desse componente, bem como o clone dos componentes que o deepsearch
estende.

Cumps.

Jorge Teixeira

2016-01-07 14:13 GMT+00:00 Rudi Luis notifications@github.com:

**Comment by jpcmt** [comment]
Não sei se já começaste a trabalhar nisto, mas fiz algumas mudanças no
ponto de extensão para simplificar.

No dia 8 de janeiro de 2016 às 09:34, Jorge Teixeira jpdcmt@gmail.com
escreveu:

**Comment by rudiluis** [comment]
Boas.. até terça estás a vontade para alterar :+1:
